version: '3.1'

networks:
  back:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
          gateway: 192.168.10.1

services:

  mongo:
    image: mongo
    restart: "no"
    ports:
      - 27017:27017
    networks:
      - back
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

#  eth-client:
#    image: ethereum/client-go:latest
#    hostname: geth
#    ports:
#      - "30303:30303"
#    expose:
#      - "8545"
#      - "8546"
#      - "6060"
#      - "8080"
#    networks:
#      - back
#    volumes:
#      - ~/Library/Ethereum:/root/.ethereum/
#    command:
#      - --ropsten
##      - --light.serve=20
#      - --syncmode
#      - "fast"
##      - --rpc
#      - --ws
#      - --ws.port=8546
#      - --ws.addr=0.0.0.0
#      - --ws.api
#      - admin,debug,web3,eth,txpool,personal,ethash,net
#      - --ws.origins="*"
#      - --metrics
#      - --metrics.addr=0.0.0.0
#      - --metrics.port=6060

  app:
    image: blockchain-service
    ports:
      - 8080:8080
    networks:
      - back
    env_file:
      - config-dev/blockchain-service.env
    environment:
      RUN_ENV: "${RUN_ENV}"
    depends_on:
      - mongo

  mongo-express:
    image: mongo-express
    restart: "no"
    ports:
      - 8081:8081
    networks:
      - back
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo
    profiles:
      - dev