FROM debian:buster-backports

RUN apt-get update -y && apt-get upgrade -y

RUN apt-get install -y software-properties-common python3-gpg

RUN add-apt-repository "deb http://ppa.launchpad.net/ethereum/ethereum/ubuntu xenial main"

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0x2A518C819BE37D2C2031944D1C52189C923F6CA9

RUN apt update -y && apt upgrade -y

RUN apt-get install -y golang-1.13 ethereum git make grep nodejs npm sed

RUN npm install -g npm@latest

RUN npm install -g truffle solc

COPY . /blockchain-service

ENV PATH=/usr/lib/go-1.13/bin:$PATH

RUN cd /blockchain-service && go mod download

ENV KEYPASSWD="password"

ENV KEYSTOREPATHSIGN="./keystore-sign"

ENV KEYSTOREPATH="./keystore"

ENV FTENDPOINT="http://127.0.0.1:8080"

ENV VALIDATIONPATH="/check-request"

ENV PATHRETRY="/check-request"

ENV NETWORKLINK="http://172.17.0.1:9545"

ENV RUNENV="Dev"

EXPOSE 8080:8080

CMD cd /blockchain-service && make compile && export ADDRESSCONTRACT=$(truffle migrate --network development | grep "contract address" | cut -c27-) && echo $ADDRESSCONTRACT && ./blockchain-service