FROM debian:buster

RUN apt-get update -y && apt-get upgrade -y

RUN apt-get install -y software-properties-common python3-gpg

RUN add-apt-repository "deb http://ppa.launchpad.net/ethereum/ethereum/ubuntu xenial main"

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0x2A518C819BE37D2C2031944D1C52189C923F6CA9

RUN apt update -y && apt upgrade -y

RUN apt-get install -y golang-go ethereum git make grep nodejs npm sed

RUN npm install -g npm@latest

RUN npm install -g truffle solc

COPY . /blockchain-service

ENV KEYPASSWD="password"

ENV KEYSTOREFILE="UTC--2020-07-16T13-52-10.535505000Z--7e12234e994384a757e2689addb2a463ccd3b47d"

ENV OFFICIALADDRESS="0x7e12234E994384A757E2689aDdB2A463ccD3B47d"

ENV KEYSTOREPATH="./keystore"

ENV NETWORKLINK="http://127.0.0.1:9545"

ENV RUNENV="Dev"

ENV DEVADDRESS="0x8718F961628D97f8d20e23Ec0e264Fd51bfD6451"

ENV DEVPRIVATEKEY="2a5c20b8657e52644b994b71d451b1a5f40188cec559e288475750710d1c54a7"

RUN make compile -C /blockchain-service

RUN CONTRACTADDRESS=$(truffle migrate | grep "contract address" | cut -c27-)

ENV ADDRESSCONTRACT=${CONTRACTADDRESS}

EXPOSE 8080:8080

CMD cd /blockchain-service && ./FtDiploma